# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/miles/Dropbox/edu/honours/code/rnastructure

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/miles/Dropbox/edu/honours/code/rnastructure

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miles/Dropbox/edu/honours/code/rnastructure/CMakeFiles /home/miles/Dropbox/edu/honours/code/rnastructure/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miles/Dropbox/edu/honours/code/rnastructure/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Fold

# Build rule for target.
Fold: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Fold
.PHONY : Fold

# fast build rule for target.
Fold/fast:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/build
.PHONY : Fold/fast

#=============================================================================
# Target rules for targets named efn2

# Build rule for target.
efn2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 efn2
.PHONY : efn2

# fast build rule for target.
efn2/fast:
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/build
.PHONY : efn2/fast

efn2/efn2.o: efn2/efn2.cpp.o

.PHONY : efn2/efn2.o

# target to build an object file
efn2/efn2.cpp.o:
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/efn2/efn2.cpp.o
.PHONY : efn2/efn2.cpp.o

efn2/efn2.i: efn2/efn2.cpp.i

.PHONY : efn2/efn2.i

# target to preprocess a source file
efn2/efn2.cpp.i:
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/efn2/efn2.cpp.i
.PHONY : efn2/efn2.cpp.i

efn2/efn2.s: efn2/efn2.cpp.s

.PHONY : efn2/efn2.s

# target to generate assembly for a file
efn2/efn2.cpp.s:
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/efn2/efn2.cpp.s
.PHONY : efn2/efn2.cpp.s

fold/Fold.o: fold/Fold.cpp.o

.PHONY : fold/Fold.o

# target to build an object file
fold/Fold.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/fold/Fold.cpp.o
.PHONY : fold/Fold.cpp.o

fold/Fold.i: fold/Fold.cpp.i

.PHONY : fold/Fold.i

# target to preprocess a source file
fold/Fold.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/fold/Fold.cpp.i
.PHONY : fold/Fold.cpp.i

fold/Fold.s: fold/Fold.cpp.s

.PHONY : fold/Fold.s

# target to generate assembly for a file
fold/Fold.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/fold/Fold.cpp.s
.PHONY : fold/Fold.cpp.s

src/ParseCommandLine.o: src/ParseCommandLine.cpp.o

.PHONY : src/ParseCommandLine.o

# target to build an object file
src/ParseCommandLine.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/ParseCommandLine.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/ParseCommandLine.cpp.o
.PHONY : src/ParseCommandLine.cpp.o

src/ParseCommandLine.i: src/ParseCommandLine.cpp.i

.PHONY : src/ParseCommandLine.i

# target to preprocess a source file
src/ParseCommandLine.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/ParseCommandLine.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/ParseCommandLine.cpp.i
.PHONY : src/ParseCommandLine.cpp.i

src/ParseCommandLine.s: src/ParseCommandLine.cpp.s

.PHONY : src/ParseCommandLine.s

# target to generate assembly for a file
src/ParseCommandLine.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/ParseCommandLine.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/ParseCommandLine.cpp.s
.PHONY : src/ParseCommandLine.cpp.s

src/RNA.o: src/RNA.cpp.o

.PHONY : src/RNA.o

# target to build an object file
src/RNA.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/RNA.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/RNA.cpp.o
.PHONY : src/RNA.cpp.o

src/RNA.i: src/RNA.cpp.i

.PHONY : src/RNA.i

# target to preprocess a source file
src/RNA.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/RNA.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/RNA.cpp.i
.PHONY : src/RNA.cpp.i

src/RNA.s: src/RNA.cpp.s

.PHONY : src/RNA.s

# target to generate assembly for a file
src/RNA.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/RNA.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/RNA.cpp.s
.PHONY : src/RNA.cpp.s

src/TProgressDialog.o: src/TProgressDialog.cpp.o

.PHONY : src/TProgressDialog.o

# target to build an object file
src/TProgressDialog.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/TProgressDialog.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/TProgressDialog.cpp.o
.PHONY : src/TProgressDialog.cpp.o

src/TProgressDialog.i: src/TProgressDialog.cpp.i

.PHONY : src/TProgressDialog.i

# target to preprocess a source file
src/TProgressDialog.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/TProgressDialog.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/TProgressDialog.cpp.i
.PHONY : src/TProgressDialog.cpp.i

src/TProgressDialog.s: src/TProgressDialog.cpp.s

.PHONY : src/TProgressDialog.s

# target to generate assembly for a file
src/TProgressDialog.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/TProgressDialog.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/TProgressDialog.cpp.s
.PHONY : src/TProgressDialog.cpp.s

src/algorithm.o: src/algorithm.cpp.o

.PHONY : src/algorithm.o

# target to build an object file
src/algorithm.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/algorithm.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/algorithm.cpp.o
.PHONY : src/algorithm.cpp.o

src/algorithm.i: src/algorithm.cpp.i

.PHONY : src/algorithm.i

# target to preprocess a source file
src/algorithm.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/algorithm.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/algorithm.cpp.i
.PHONY : src/algorithm.cpp.i

src/algorithm.s: src/algorithm.cpp.s

.PHONY : src/algorithm.s

# target to generate assembly for a file
src/algorithm.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/algorithm.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/algorithm.cpp.s
.PHONY : src/algorithm.cpp.s

src/alltrace.o: src/alltrace.cpp.o

.PHONY : src/alltrace.o

# target to build an object file
src/alltrace.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/alltrace.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/alltrace.cpp.o
.PHONY : src/alltrace.cpp.o

src/alltrace.i: src/alltrace.cpp.i

.PHONY : src/alltrace.i

# target to preprocess a source file
src/alltrace.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/alltrace.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/alltrace.cpp.i
.PHONY : src/alltrace.cpp.i

src/alltrace.s: src/alltrace.cpp.s

.PHONY : src/alltrace.s

# target to generate assembly for a file
src/alltrace.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/alltrace.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/alltrace.cpp.s
.PHONY : src/alltrace.cpp.s

src/arrayclass.o: src/arrayclass.cpp.o

.PHONY : src/arrayclass.o

# target to build an object file
src/arrayclass.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/arrayclass.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/arrayclass.cpp.o
.PHONY : src/arrayclass.cpp.o

src/arrayclass.i: src/arrayclass.cpp.i

.PHONY : src/arrayclass.i

# target to preprocess a source file
src/arrayclass.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/arrayclass.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/arrayclass.cpp.i
.PHONY : src/arrayclass.cpp.i

src/arrayclass.s: src/arrayclass.cpp.s

.PHONY : src/arrayclass.s

# target to generate assembly for a file
src/arrayclass.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/arrayclass.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/arrayclass.cpp.s
.PHONY : src/arrayclass.cpp.s

src/forceclass.o: src/forceclass.cpp.o

.PHONY : src/forceclass.o

# target to build an object file
src/forceclass.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/forceclass.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/forceclass.cpp.o
.PHONY : src/forceclass.cpp.o

src/forceclass.i: src/forceclass.cpp.i

.PHONY : src/forceclass.i

# target to preprocess a source file
src/forceclass.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/forceclass.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/forceclass.cpp.i
.PHONY : src/forceclass.cpp.i

src/forceclass.s: src/forceclass.cpp.s

.PHONY : src/forceclass.s

# target to generate assembly for a file
src/forceclass.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/forceclass.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/forceclass.cpp.s
.PHONY : src/forceclass.cpp.s

src/outputconstraints.o: src/outputconstraints.cpp.o

.PHONY : src/outputconstraints.o

# target to build an object file
src/outputconstraints.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/outputconstraints.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/outputconstraints.cpp.o
.PHONY : src/outputconstraints.cpp.o

src/outputconstraints.i: src/outputconstraints.cpp.i

.PHONY : src/outputconstraints.i

# target to preprocess a source file
src/outputconstraints.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/outputconstraints.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/outputconstraints.cpp.i
.PHONY : src/outputconstraints.cpp.i

src/outputconstraints.s: src/outputconstraints.cpp.s

.PHONY : src/outputconstraints.s

# target to generate assembly for a file
src/outputconstraints.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/outputconstraints.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/outputconstraints.cpp.s
.PHONY : src/outputconstraints.cpp.s

src/rna_library.o: src/rna_library.cpp.o

.PHONY : src/rna_library.o

# target to build an object file
src/rna_library.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/rna_library.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/rna_library.cpp.o
.PHONY : src/rna_library.cpp.o

src/rna_library.i: src/rna_library.cpp.i

.PHONY : src/rna_library.i

# target to preprocess a source file
src/rna_library.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/rna_library.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/rna_library.cpp.i
.PHONY : src/rna_library.cpp.i

src/rna_library.s: src/rna_library.cpp.s

.PHONY : src/rna_library.s

# target to generate assembly for a file
src/rna_library.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/rna_library.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/rna_library.cpp.s
.PHONY : src/rna_library.cpp.s

src/stackclass.o: src/stackclass.cpp.o

.PHONY : src/stackclass.o

# target to build an object file
src/stackclass.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/stackclass.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/stackclass.cpp.o
.PHONY : src/stackclass.cpp.o

src/stackclass.i: src/stackclass.cpp.i

.PHONY : src/stackclass.i

# target to preprocess a source file
src/stackclass.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/stackclass.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/stackclass.cpp.i
.PHONY : src/stackclass.cpp.i

src/stackclass.s: src/stackclass.cpp.s

.PHONY : src/stackclass.s

# target to generate assembly for a file
src/stackclass.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/stackclass.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/stackclass.cpp.s
.PHONY : src/stackclass.cpp.s

src/stackstruct.o: src/stackstruct.cpp.o

.PHONY : src/stackstruct.o

# target to build an object file
src/stackstruct.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/stackstruct.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/stackstruct.cpp.o
.PHONY : src/stackstruct.cpp.o

src/stackstruct.i: src/stackstruct.cpp.i

.PHONY : src/stackstruct.i

# target to preprocess a source file
src/stackstruct.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/stackstruct.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/stackstruct.cpp.i
.PHONY : src/stackstruct.cpp.i

src/stackstruct.s: src/stackstruct.cpp.s

.PHONY : src/stackstruct.s

# target to generate assembly for a file
src/stackstruct.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/stackstruct.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/stackstruct.cpp.s
.PHONY : src/stackstruct.cpp.s

src/structure.o: src/structure.cpp.o

.PHONY : src/structure.o

# target to build an object file
src/structure.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/structure.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/structure.cpp.o
.PHONY : src/structure.cpp.o

src/structure.i: src/structure.cpp.i

.PHONY : src/structure.i

# target to preprocess a source file
src/structure.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/structure.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/structure.cpp.i
.PHONY : src/structure.cpp.i

src/structure.s: src/structure.cpp.s

.PHONY : src/structure.s

# target to generate assembly for a file
src/structure.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/structure.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/structure.cpp.s
.PHONY : src/structure.cpp.s

src/thermodynamics.o: src/thermodynamics.cpp.o

.PHONY : src/thermodynamics.o

# target to build an object file
src/thermodynamics.cpp.o:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/thermodynamics.cpp.o
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/thermodynamics.cpp.o
.PHONY : src/thermodynamics.cpp.o

src/thermodynamics.i: src/thermodynamics.cpp.i

.PHONY : src/thermodynamics.i

# target to preprocess a source file
src/thermodynamics.cpp.i:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/thermodynamics.cpp.i
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/thermodynamics.cpp.i
.PHONY : src/thermodynamics.cpp.i

src/thermodynamics.s: src/thermodynamics.cpp.s

.PHONY : src/thermodynamics.s

# target to generate assembly for a file
src/thermodynamics.cpp.s:
	$(MAKE) -f CMakeFiles/Fold.dir/build.make CMakeFiles/Fold.dir/src/thermodynamics.cpp.s
	$(MAKE) -f CMakeFiles/efn2.dir/build.make CMakeFiles/efn2.dir/src/thermodynamics.cpp.s
.PHONY : src/thermodynamics.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... Fold"
	@echo "... rebuild_cache"
	@echo "... efn2"
	@echo "... efn2/efn2.o"
	@echo "... efn2/efn2.i"
	@echo "... efn2/efn2.s"
	@echo "... fold/Fold.o"
	@echo "... fold/Fold.i"
	@echo "... fold/Fold.s"
	@echo "... src/ParseCommandLine.o"
	@echo "... src/ParseCommandLine.i"
	@echo "... src/ParseCommandLine.s"
	@echo "... src/RNA.o"
	@echo "... src/RNA.i"
	@echo "... src/RNA.s"
	@echo "... src/TProgressDialog.o"
	@echo "... src/TProgressDialog.i"
	@echo "... src/TProgressDialog.s"
	@echo "... src/algorithm.o"
	@echo "... src/algorithm.i"
	@echo "... src/algorithm.s"
	@echo "... src/alltrace.o"
	@echo "... src/alltrace.i"
	@echo "... src/alltrace.s"
	@echo "... src/arrayclass.o"
	@echo "... src/arrayclass.i"
	@echo "... src/arrayclass.s"
	@echo "... src/forceclass.o"
	@echo "... src/forceclass.i"
	@echo "... src/forceclass.s"
	@echo "... src/outputconstraints.o"
	@echo "... src/outputconstraints.i"
	@echo "... src/outputconstraints.s"
	@echo "... src/rna_library.o"
	@echo "... src/rna_library.i"
	@echo "... src/rna_library.s"
	@echo "... src/stackclass.o"
	@echo "... src/stackclass.i"
	@echo "... src/stackclass.s"
	@echo "... src/stackstruct.o"
	@echo "... src/stackstruct.i"
	@echo "... src/stackstruct.s"
	@echo "... src/structure.o"
	@echo "... src/structure.i"
	@echo "... src/structure.s"
	@echo "... src/thermodynamics.o"
	@echo "... src/thermodynamics.i"
	@echo "... src/thermodynamics.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

